exclude: "docs|notebooks|node_modules|.vscode|.venv|.git|.tox|.pytest_cache"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args:
          [
            "--config-file",
            "pyproject.toml",
            "--python-executable",
            ".venv/bin/python",
          ]
        files: ^src/

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-file", "pyproject.toml"]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]
